name: "Hit a webhook"
on:
  push:
    tags:
      - '**'
      
  #workflow_dispatch:
  #  types:
  #    - webhook
  #    - '**'
  
  repository_dispatch:
    types:
      - webhook
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: echo
        shell: bash
        run: |
          curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN_TEST }}" --data '{"event_type": "makepkg", "client_payload": { "version": "1.2.3"}}'   https://api.github.com/repos/gitbigbarna/ac-test/dispatches
        ### Tmate ##
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3 
